spring:
  application:
    name: sample-prometheus-grafana
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB
    username: test
    password:
  h2:
    console:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}

server:
  port: 8099
