global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'sample-prometheus-grafana'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: [ 'host.docker.internal:8099' ]
        labels:
          app: 'sample-prometheus-grafana'